"""Third Migration

Revision ID: 04a6acab554a
Revises: 5882253f10df
Create Date: 2019-07-02 11:52:35.403222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a6acab554a'
down_revision = '5882253f10df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_title', sa.String(length=100), nullable=False),
    sa.Column('pitch_category', sa.String(length=255), nullable=True),
    sa.Column('pitch_content', sa.String(length=255), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('hash_pass', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'image_file')
    op.drop_column('users', 'hash_pass')
    op.drop_table('pitches')
    # ### end Alembic commands ###
